on:
  workflow_dispatch:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: 'addy2908/devops-project'
          fetch-depth: 1 
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*    
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.2.1
        with:
          java-version: 8

      - name: Build with Maven
        run: mvn verify    