on:
  workflow_dispatch:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: 'addy2908/devops-project'
          fetch-depth: 1 
          ref: maven-release-0.1.9
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*    


      - run: |
          sudo apt install maven
          ls -la

      - run: sudo mvn clear install