name: 'tag'
on: workflow_dispatch
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
        repository: 'https://github.com/addy2908/devops-project.git'
    - uses: christophebedard/tag-version-commit@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        version_tag_prefix: 'v'