name: Test 
on: workflow_dispatch
jobs:
  print:
    runs-on: Ubuntu-latest
    steps:
    - name: testname
      run: |
        ls -la
        gh repo clone actions/go-dependency-submission
        ls -la
        cd ./go-dependency-submission
        ls -la
      env:
          GITHUB_TOKEN: ${{ github.token }}    
