name: Test 
on: workflow_dispatch
jobs:
  print:
    runs-on: Ubuntu-latest
    steps:
    - name: testname
    - run: ls -la
    - run: gh repo clone actions/go-dependency-submission
    - run: ls -la
